version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - data:/data
    user: root
    entrypoint:
      - /surreal
      - start
      - --user
      - $DB_ROOT_USER
      - --pass
      - $DB_ROOT_PASSWORD
      - rocksdb:/data/rocksdb.db

volumes:
  data:
